### ISSUE TITLE
No usable OpenSSL found on mac os el capitan

### ISSUE THREAD

**Issue by yanovitchsky** [robisonsantos/evm#18]
Is it possible to pass option to the install command  like ssl lib path?

ex. evm install OTP_18.3 --with-ssl=/usr/local/opt/openssl/

**Comment by robisonsantos** [comment]
No with current implementation, but I can try to get it working.

**Comment by robisonsantos** [comment]
You can now pass any "configure" parameter to evm install.
Hope this fix your issue.
