### ISSUE TITLE
`evm installed` output

### ISSUE THREAD

**Issue by 7stud** [robisonsantos/evm#22]
I think I'm getting a bash error:
```
~$ evm installed
Installed Erlang versions on this system

-bash: unalias: ls: not found   //<==HERE
19.2

------
=* : current and default
=> : current
 * : default
```

OSX 10.10.5
~$ evm version
4.0.4

**Comment by robisonsantos** [comment]
What's your OS?  I'll try to fix this soon as possible.

Meanwhile you can remove that line from your EVM script.

**Comment by 7stud** [comment]
It's at the bottom of my post: OSX 10.10.5.

**Comment by robisonsantos** [comment]
Issues fixed. 
Redirecting the output of 'unalias' to /dev/null to avoid showing error messages to terminal
