### ISSUE TITLE
`evm installed` outputs illegal characters

### ISSUE THREAD

**Issue by 7stud** [robisonsantos/evm#23]
OSX 10.10.5
$ evm version
4.0.4

Here is the output from `evm installed` before choosing an erlang version:
```
~/.evm/scripts$ evm installed
Installed Erlang versions on this system

19.2

------
=* : current and default
=> : current
 * : default
```

Then I choose the erlang version:

    ~$ evm use 19.2

And now the problem reveals itself:

```
~$ evm installed
Installed Erlang versions on this system

\e[1;32m=> 19.2\e[0m     //<===HERE

------
=* : current and default
=> : current
 * : default
```

I'm using OSX's Terminal app, and I have the "text encoding" setting (under Preferences>Profiles>Advanced Tab) set to `UTF-8`.

I tried changing my terminal's encoding to Latin-1, but I get the exact same output.

**Comment by robisonsantos** [comment]
Thanks for reporting it. I believe this is not affecting your usage of the
script.

I know the issue and will fix it soon.

**Comment by robisonsantos** [comment]
The problem here is probably your terminal does not have colors enabled. You can try this: http://osxdaily.com/2013/02/05/improve-terminal-appearance-mac-os-x/ to have colors enabled.

Meanwhile I'll fix the code to only show colors it they are enabled.

**Comment by robisonsantos** [comment]
I just remembered (and checked) that I have already a check to see if the terminal supports color before trying to print them.

**Comment by robisonsantos** [comment]
But the code is wrong. I'm fixing it now.

**Comment by robisonsantos** [comment]
Fixed the issue.
Updated code to verify when current terminal has colors support.

**Comment by 7stud** [comment]
My terminal does have color support.  For example, rvm (ruby version manager) outputs colors in my terminal.  I just ran ```$ rvm list```, and there are colors.

By the way, what is the procedure for updating evm?

**Comment by robisonsantos** [comment]
At the moment you just need to install it again.
