### ISSUE TITLE
Failed to fetch available Erlang versions

### ISSUE THREAD

**Issue by EdoardoLopez** [robisonsantos/evm#35]
Hi recently i have a problem listing Erlang versions, i can't list or download any version of Erlang
here adjunct a picture with some information and error.

![Screenshot from 2020-12-20 13-16-57](https://user-images.githubusercontent.com/11698234/102721079-7b07d200-42c6-11eb-827c-febf546e5838.png)

Thanks!

**Comment by robisonsantos** [comment]
I just tried it and it worked fine for me. Can you try installing the latest version `5.0.0`  and try again?

You can clone the repository and `./install` it again. It will replace the scripts, but will keep all installed erlang versions.

Let me know if that is still not working.

**Comment by EdoardoLopez** [comment]
Don't affect if i have previous OTP versions installed?

**Comment by robisonsantos** [comment]
That's right, it should not affect those erlang versions already installed.

If you want to be super safe, you can create a backup of evm before you install the new version

```
cp -r ~/.evm ~/.evm_bkp
git clone https://github.com/robisonsantos/evm
cd evm
./install
``` 

If that works as you expect, you can delete your backup `rm -r ~/.evm_bkp`

**Comment by EdoardoLopez** [comment]
yep it works now, thanks!!.
I was have to reboot my machine to load the new version of evm. very thanks for your time and help!.
