### ISSUE TITLE
Depends on `shopt`

### ISSUE THREAD

**Issue by simonmeulenbeek** [robisonsantos/evm#40]
Using EVM with Zsh fails because Zsh doesn't provide `shopt`.

Workaround: switching to bash before using EVM.

**Comment by robisonsantos** [comment]
Which OS are you using?

**Comment by robisonsantos** [comment]
I tested the fix on my mac and the error goes away. Please try again with the latest version of evm.

**Comment by simonmeulenbeek** [comment]
This works perfectly now!

**Comment by robisonsantos** [comment]
I was able to reproduce the issue. I'll fix it shortly
