### ISSUE TITLE
`set -o errexit` affects all Bash usage after sourcing

### ISSUE THREAD

**Issue by giang-nghg** [robisonsantos/evm#43]
I wonder if adding this means the `evm` script is not supposed to be sourced anymore, or an `unset` of this option is needed at the end of the script? Because currently, after the script has done its job, the shell is still set to exit upon _any_ errors, like mistyping a command.

At least observed on:
- Windows Subsystem for Linux version: Windows 10 build 19044
- Distro: Ubuntu 18.04.5 on Windows
- Kernel version: 5.10.16.3-microsoft-standard-WSL2
- Bash version:  4.4.20(1)-release (x86_64-pc-linux-gnu)

**Comment by giang-nghg** [comment]
Quick fix for anyone having this problem like me: Add `set +o errexit` after sourcing `evm`

**Comment by robisonsantos** [comment]
I removed that line now. I'll find a better way to handle the errors only within the functions without too many boilerplate

**Comment by robisonsantos** [comment]
Oh, that's a bug. I'll send the fix in a few minutes.
